### ISSUE TITLE
use admonition for Conformance Criteria

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#11]
Rather than bolding **Conformance Criteria:**, use a proper admonition block

.. admonition:: And, by the way...

   You can make up your own admonition too.

**Comment by monkeypants** [comment]
Suggest four new directives:

 * conformance_should
 * conformance_must
 * conformance_must_list
 * conformance_should_list

where conformance_should and conformance_must both make an admonition block, and the *_list directives produce something like a "self assessment check-list" (thereby closing #9).

**Comment by chris-beer** [comment]
Why not additionally tie conformance formally to http://www.ietf.org/rfc/rfc2119.txt (Key words) to remove ambiguity and bring it in line with related standards like the ISM and industry specs (for agencies going to market for instance).

**Comment by monkeypants** [comment]
Absolutely, SHOULD and MUST are key differentiators. 

The idea was to assert (with a special markup directive) a conformance criteria in context. These would be rendered out appropriately in context, and also available to render a checklist.

If that was possible, it might also be possible to render other "checklist" type outputs, e.g. JSON for the purpose of interactive self-assessment applications, complain-that-a-service-doesn't-comply features, etc.

**Comment by chris-beer** [comment]
It is a good idea IMO.

Thinking out loud - Re: markup for checklists and conformance tests etc - have you looked at Evaluation and Report Language (EARL) - (http://www.w3.org/TR/EARL10-Schema/ and http://www.w3.org/WAI/intro/earl.php )? Something like that might be a way to approach it if you want to go fully interactive on self-assessment.

"EARL is a vocabulary, the terms of which are defined across a set of specifications and technical notes, that is used to describe test results in a machine-readable format."

**Comment by monkeypants** [comment]
Nice one, thanks. I'll check EARL out.

**Comment by monkeypants** [comment]
The above commit is an collection of yaml files (named ".crit"), with the idea that they could be generated from custom "conformance criteria" directives in a rst repository, or manually maintained in a simpler markdown repository, and used for hybrid markup documentation publishing, as well as other applications (self-assessment checklists, non-conformance reporting apps, etc).

It's a rough sketch of an idea at this stage. Might also be good to think about versioning, release management and other governance aspects of individual conformance criteria. i.e. other attributes to the .crit file (status, approval date, review date, etc). Could/Should they be managed as individual ".crit files"/markup directives? What are some other options?

Here's a diagram of how our publishing tool-chain may look if we went down this path:
![tmp](https://cloud.githubusercontent.com/assets/532596/9581256/ae9e8442-5041-11e5-81eb-6cf2f61f09b5.png)

**Comment by monkeypants** [comment]
@chris-beer by the way, I did look at EARL and agree it's a potentially interesting way to express the results of assessment against the applicable conformance criteria. Did you mean to suggest using it in that way, or going further (e.g. using RDF-based tools for recording conformance self-assessment, stakeholder reporting of conformance issues, and compliance activities)?

I haven't had much to do with WCAG conformance stuff and don't know how that's implemented or works in practice. I think maybe there is similar potential scope for automated validation in the API domain as with accessibility, but am not aware of equivalent ecosystem of tools.

**Comment by chris-beer** [comment]
Re: Last - they originally put it forward I believe as part of the ATAG work (automated tool testing) so agree - similar potential scope.

I meant it more as the former (in that "an API is a type of interface by any other name so here is a possible existing approach") but yes - the end game could certainly be along those lines - indeed expressed as you have, I'm seeing a WoG approach for conformance for ATM applications, post-implementation reviews of ICT projects - the potential could be endless as far as automated checking goes.

(Haven't had time to look at the yaml files btw but will asap :) )

**Comment by monkeypants** [comment]
Hold fire on spending to much effort looking at the yaml (although it's pretty simple); Concerned about the complexity of the deployment/workflow diagram above, I'm tinkering with a sphinx extension that might be better. (https://github.com/monkeypants/sphinx.rfc2119)

**Comment by monkeypants** [comment]
OK, the rfc2119 module is ready to use (I think). http://sphinxrfc2119.readthedocs.org

I'm closing this ticket because it's superseded by:

 * #44 sphinx.rfc2119 refactor
 * #45 yaml builder for rfc2119 requirements
