### ISSUE TITLE
SemVer !!!

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#19]
following on from #18... http://semver.org/ !!!

**Comment by chris-beer** [comment]
+1 - was sort of suprised that it didn't get a mention in either section.

**Comment by monkeypants** [comment]
It made it to the whiteboard, we just didn't write it up yet. Apparently this wasn't adequate: "there use to be a few different standards, SemVer won. Use it unless you have a really good reason not to"

**Comment by jpiulac** [comment]
+1
