### ISSUE TITLE
cors.rst is too lightweight

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#26]
the cors.rst document does not have enough content:
- link to relevant documents
- say more about what cores is, why it matters, when/how to use it
- why cors not jsonp (etc).

**Comment by markmuir87** [comment]
Although I've consumed jsonp in the past, I'm not very clear on the technical merits of either approach. All I can say is that jsonp seems like a bit of a hack to get around cross-domain call restrictions in browsers (by wrapping json payloads in JS functions). I've heard vague rumblings that jsonp is 'less secure' but have never heard why that is the case (unless we're talking about people blindly using eval() on returned jsonp, which would be a pretty dumb thing to do). If this is the concern, it shouldn't be as much of a concern with government: I couldn't imagine a government API injecting malicious JS into returned jsonp.

When I find the time, I'll try to do a bit more reading on the subject and get back to you guys with a more definitive answer.
