### ISSUE TITLE
add GA code to RTD config

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#27]
it would be nice to know how much traffic the RTD site is getting

**Comment by monkeypants** [comment]
http://www.drmaciver.com/2015/04/getting-google-analytics-on-readthedocs/

@mmck-dto, what's the right GA code to use?

**Comment by markmuir87** [comment]
Just to speed things up for @mmck-dto, here's what the link says:
```
The correct way to add google analytics to your readthedocs instance is as follows:

* Go to the Admin page for your project
* Click on “Advanced settings”
* Enter your Google Analytics Tracking ID in the box at the bottom that says “Analytics ID”
```

**Comment by markmuir87** [comment]
Hey Simon, I've assigned this issue to you as I understand you have the DTO GA ID. When you get a chance, could you talk to Mark McKenzie so that he can add it to our 'readthedocs' instance?

**Comment by monkeypants** [comment]
Should we use the same DTO GA ID for multiple readthedocs sites, or should we have a different one per site?

If it's the same as the regular DTO site, from [ctl]-u it looks like it might be "UA-54970022-1".

I'm happy to configure readthedocs, I just need to know the right GA ID to use. (anyone else want to have admin on readthedocs let me know, it's just me and @mmck-dto at the moment)
