### ISSUE TITLE
Simplify preface and improve language flow

### ISSUE THREAD

**Issue by markmuir87** [AusDTO/apiguide#31]
Please review pull request: https://github.com/AusDTO/apiguide/pull/30

I haven't changed the substance of the message, but have altered the language to hopefully appeal to a broader audience (as I understand this will be converted into a blog post at some stage).

**Comment by monkeypants** [comment]
Merged, thanks Mark!

note: if you name the branch <ticketnumber>-*, then waffle.io magic moves the kanban task about for you. Also, comments "fixes #30" automagically closes the ticket when the pull request is merged.
