### ISSUE TITLE
pandoc filtering for MD integration

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#35]
The rest of the Design Guides / Digital Service Standard are moving towards markdown, possibly through prose.io and/or editing directly through github.

API Guide is in rst, which is nice and has advantages if #11 etc. However if everyone else is using markdown we should probably convert to it.

Perhaps with pandoc (http://hackage.haskell.org/package/pandoc) and a few tricks (e.g. https://github.com/jgm/pandocfilters), maybe we can have our cake and eat it too? I mean, maybe we could produce satisfactory markdown for incorporation into the DSS from the apiguide rst, and use git and pandoc to incorporate text changes to flow back the other way?

Alternatively, if markdown has an suitable mechanism for doing something like #11, we could just switch completely.

**Comment by onthebreeze** [comment]
https://aaronparecki.com/articles/2012/09/01/1/some-enhancements-to-markdown
