### ISSUE TITLE
HTTP response principles example doesn't make sense

### ISSUE THREAD

**Issue by clockwisemusic** [AusDTO/apiguide#41]
On the "Building and using APIs" page under "HTTP response principles" it says:

*No values in keys – for example, {“125”: “Environment”} is bad, {“id”: “125”, “name”: “Environment”} is good.*

But I think you might mean 

{“125”, “Environment”} is bad, {“id”: “125”, “name”: “Environment”} is good.

**Comment by nokout** [comment]
Thanks for the heads up @clockwisemusic should be all fixed now.

**Comment by clockwisemusic** [comment]
Looks good, that was quick!

**Comment by monkeypants** [comment]
Actually, I think it was right the first time :/

The first (bad) example is not a list, it's a dictionary where the key is "123" and the value is "Environment". That's bad because the key should label the concept, not encode a different value.

**Comment by monkeypants** [comment]
fixed again with ed40d49aa603334b16c39eae6e10793e936dc805
