### ISSUE TITLE
AusDTO blog post <- preface.rst

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#5]
following #3, which depends on #2 (and preferably also after #4), convince the DTO communications chaps to publish the contents of preface.rst through the official megaphone.

**Comment by markmuir87** [comment]
Also depends on [#31](https://github.com/AusDTO/apiguide/issues/31)

**Comment by monkeypants** [comment]
whoops, should have closed this ticket when the blog was published
