### ISSUE TITLE
resolve API register idea

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#50]
principles/empathy.rst used to contain the following text:

```
To ensure dicoverability and accountability, all Government APIs will be published to a
central service register (as described in Building and Publishing APIs secion [insert link]).
The service register will give developers a mechanism to provide feedback on APIs. 
```

That's a nice idea but it doesn't exist, and there is no firm policy around it. This ticket is to resolve the position, either make it real or decide not to do it.

**Comment by onthebreeze** [comment]
Currently the register is a file on data.gov.au

So it exists but it's s bit "light"

Steve Capell
Mob: 0410 437854

**Comment by monkeypants** [comment]
Can you provide a link?

**Comment by monkeypants** [comment]
principles/discoverability.rst also used to contain the following text:

    To ensure dicoverability and accountability, all Government APIs will be published
    to a central service register (as described in Building and Publishing APIs secion [insert link]).
    The service register will give developers a mechanism to provide feedback on APIs. 

This was also an aspiration re: #50 

The removed text also references linking to API documentation from the register.
