### ISSUE TITLE
apiguide/principles/security.rst is not consistent with NeAF guidelines.

### ISSUE THREAD

**Issue by gitcnd** [AusDTO/apiguide#62]
You must use level 3 or above if (among other reasons) there is any chance of damage to any persons reputation, or distress to any party:

Parking permits contain home addresses.
Tax returns contain financial and other information.
Tax File Number exposure would assist in identity crime.
Balance enquiry exposure stands a god chance of embarrassing people.
Private data validation - see that first word there?

Every single example listed is not suitable for Assurance Level 2, improperly securing any of those things will absolutely lead to distress or reputation damage.

**Comment by monkeypants** [comment]
I don't have write access to this repository any more, but still appreciate the feedback and hope to see the document improved!

I'm not going to disagree with the risk assessment of those hypothetical examples; To be honest, I can't even remember the scenarios we were thinking of when we wrote it :)  So it's not fair to expect the reader to assess consequences or probability, your assessment is as valid as any other.

My reading of NeAF is that consequences and likelihood are assessed using AS/NZ 4360, which has specific levels of severity for reputation and distress. For example, "minor or short term" damage to reputation (or distress) is classified as a "Moderate" severity consequence. Where the likelihood of moderate severity consequence is "possible, unlikely or rare", then NeAF proscribes (LoA 2). An interpretation that rates "rare likelihood of minor or short term distress" as requiring "moderate confidence in the identity assertion" (LoA 3) seems to me to be more conservative than NeAF.

Of course, if the likelihood was higher than "possible" or the consequence was higher than "moderate", then LoA 3 would be called for (possibly LoA 4, in the case major consequence was likely, or severe consequence was possible).

So, what's a better example that would illustrates when LoA 2 is appropriate?

**Comment by gitcnd** [comment]
Maybe we're looking at different NeAF documents?  For both distress and reputation, LoA2 is only appropriate for "none" - LoA 3 is prescribed for "possible, unlikely or rare" (moderate) severity level on both of those.

If nothing else - it's common sense.  When someones tax data, private information, or home address gets hacked, do you want to explain to the world why nothing better than a plain password was protecting that data?

Australian citizen data is being rampantly harvested by identify thieves right now, hundreds of millions in fake tax returns are getting lodged, Census is being raked over the coals for lying about ASD security compliance and then getting hacked, and around the world, government databases are being stolen and even retributively published online when governments falsely claim otherwise (Philippines, Turkey, Israel, South Africa, ... and several times in Australia already, ), and surveys published showing some citizens are more fearful of identity theft than even things like murder and burglary.

This needs getting right.

Can you find an expert on this material (ASD?), get them write-access, and get this fixed?  

With cybercrime and privacy so high on everyone's minds now days, and with the existence of good usable strong authentication from Australian Industry, having no LoA2 access whatsoever would be a sensible recommendation in my opinion.  Look at the Census fallout: can you think of *any* kind of breach that would not result in serious harm to DTO reputation?

**Comment by monkeypants** [comment]
> with the existence of good usable strong authentication from Australian Industry, having no LoA2 access whatsoever would be a sensible recommendation

Level of assurance and authentication strength are different concepts. For example, my GitHub account that I am using right now has stronger authentication than some bank accounts (two factor auth) but very weak LoA - when I created the account, the only personally identifying information I provided was an email address. Since then my identity has become somewhat stronger due to accumulating "evidence of participation in society", but it's still essentially LoA 0.

> Maybe we're looking at different NeAF documents?

This is the one I have https://www.finance.gov.au/sites/default/files/NeAFFramework.pdf

Table 3, page 15 (22) is the consequence matrix I referred to, and Table 4, page 16 (23) is the likelihood matrix I used.

> Can you find an expert on this material (ASD?), get them write-access, and get this fixed?

Me personally? No, I don't work at DTO anymore (or ASD).

FWIW, according to this page (https://www.finance.gov.au/archive/policy-guides-procurement/authentication-and-identity-management/national-e-authentication-framework/) the NeAF better practice guides are currently under review.

In the meantime, most constructive thing we can do is propose better examples for LoA 2. Any ideas?

**Comment by gitcnd** [comment]
> assurance and authentication strength are different concepts
Yes, but security.rst has assurance in the left column, and the authentication-strength recommendation in the right column: they literally tied tax-returns, private information, addresses, etc to "single factor authentication".

Those NeAF tables are terrible. LoA3 is "Moderate" and so are reputation/distress.  Anyhow - since Census has taught us that reputation-damage in government hack events is now significantly more than "possible, unlikely or rare", that bumps all this into the "Major" or "Severe" categories anyhow.

My LoA2 proposal is to have no LoA2 access whatsoever.  The level of hacking against government systems is at epidemic levels right now: we need the DTO and agencies that take their advice to get serious about protecting us. Plain passwords, on any government-identity service simply do not cut it any more.

**Comment by monkeypants** [comment]
The #CensusFail twitter tag out-trended the Olympics; on the face of it, any claim that the public reaction to Census 2016 are in the "minor or short term" category do not seem credible.

> My LoA2 proposal is to have no LoA2 access whatsoever.

LoA 3 means "moderate confidence is required in the identity assertion".

I for one would feel significantly less secure if I had to provide "100 points of ID" just to pay a parking fine or submit a tax return. However, I have no objection to doing that when I open a bank account. I personally dislike forced disclose of more personal information than I feel is reasonably necessary for a counterparty to do their job (regardless of who the counterparty is - Government, corporate or interpersonal). I don't think I am unusual in this regard.

If you follow the "some LoA is good, so more must be better" reasoning through (over-classification bias), you end up with unnecessarily catastrophic failure scenarios. Collecting/assessing excessive personal information does not make us safer, it makes us less safe.  On the other hand, a LoA under-classification bias will make it too easy for someone to pretend to be someone they are not (that may or may not be a problem, depending on the situation).

The lower LoA classifications (0, 1 and 2) are important. The optimum LoA classification in any given situation is the best balanced compromise between privacy, convenience and the real need to know who someone actually is.
