### ISSUE TITLE
RESTful API Design Guidelines

### ISSUE THREAD

**Issue by Robinyo** [AusDTO/apiguide#64]
A DRAFT RESTful API Design Guidelines document: https://github.com/ato-team/restful-api-design-guidelines

A DRAFT OpenAPI specification: https://github.com/ato-team/business-registries-rest-api-specification

A ReDoc rendering of the specification: https://ato-team.github.io/business-registries-rest-api-specification/

**Comment by monkeypants** [comment]
Nice! i would suggest making a Pull Request to link to those from this document, however it might be futile. There are already 5 unanswered PRs, apparently this apiguide is unmaintained (I no longer have access).
