### ISSUE TITLE
decouple document system from rest of DEV environment

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/apiguide#7]
Right now, these docs build out fine on my DEV machine and in my CI environment, but there is probably unknown pain for future contributors to get a document build-out going like mine.  

Should definitely move the Dockerfile into this repo and make sure it's cleanly separated from the rest of the DEV environment. Might also be good opportunity to clean up all the latex package dependencies, graphviz, etc. Make sure everything works comes up and works from a fresh install.

Rather than documenting our CI setup, it might be better to refactor the logic out of config and into a script that serves as a wrapper/documentation (so CI just runs the script, that's it).

**Comment by markmuir87** [comment]
Might this just be a matter of syntax and logical organisation of the repo? So root level would just be a README.md file, with first-level folders separating the documentation content and config files? Whatever arrangement we settle on, I assume our guiding principle is to make it as easy as possible for others to collaboratively edit? (though small technical hurdles aren't too big a deal, given collaborators are likely to be of the technical sort...)
